### ISSUE TITLE
Latin Capital Letter I With Diaeresis

### ISSUE THREAD

**Issue by jeffmcneill** [Holger-Will/code-128-font#2]
I'm encoding with code128 which generates:

Ò3FI83ÏÓ
from
1938412419

However, the display is not correct for Ï, see attached: the font display for code128_L leaves a large gap and can't be read by code128 readers.

![latin-capital-i-diaeresis-2](https://user-images.githubusercontent.com/3119827/48930188-7030b680-ef21-11e8-80b0-bd859d10aee1.png)

![latin-capital-a-diaeresis](https://user-images.githubusercontent.com/3119827/48930189-7030b680-ef21-11e8-9b87-a7a46d8b2596.png)

**Comment by Holger-Will** [comment]
should be fixed now... had the fix for it in barcode-font-generator but did not get around fixing these fonts here. thanks for the report!

**Comment by jeffmcneill** [comment]
Hi, I've tried these new fonts but they just have a latin uppercase i diaeresis rather than a bar code, and now the capital O acute and capital O grave also do not have bars, but the extended latin character for each. 

![image](https://user-images.githubusercontent.com/3119827/48945159-f0740d80-ef5b-11e8-8641-d41b58ed2632.png)

**Comment by Holger-Will** [comment]
make sure to update the encoder as well. i had to change quite a bit because of some strange  mapping info on wikipedia... https://github.com/graphicore/librebarcode/issues/9

**Comment by Holger-Will** [comment]
your encoded string should now be: Í3FI83ÊÎ and should render well with my font as well as with the fonts found on google fonts etc.

**Comment by Holger-Will** [comment]
you see it working here: https://holger-will.github.io/code-128-encoder/examples/html/encoder.html

**Comment by jeffmcneill** [comment]
Great, that worked.Thanks for your amazingly speedy response. These two apps help me a lot. I use them to generate ASIN barcodes for Amazon. Since the ASINs are effectively ISBN-10 codes, other people's scripts detect that and generate the full-blown ISBN barcode. By breaking out the encoding part, and then using a font to display the code, this solves my problem and I can manage the codes easily in Inkscape.

**Comment by Holger-Will** [comment]
that is exactly the usecase i wrote this for ;-) cheers!
